#ifndef PIN_H_INCLUDED
#define PIN_H_INCLUDED

#define PIN_ALIM 29
#define PIN_SONNETTE 1
#define PIN_POMPE 4
#define PIN_CHAUFFAGE 28
#define PIN_ALIM_CAPTEUR_TEMPERATURE 5
#define PIN_PURGE_CONDENSATEUR 6

#endif // PIN_H_INCLUDED
